apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeaiwhisperer-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeaiwhisperer-cluster-role
rules:
- apiGroups: ["", "apps"]
  resources: ["namespaces", "deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeaiwhisperer-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: kubeaiwhisperer-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubeaiwhisperer-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeaiwhisperer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeaiwhisperer
  template:
    metadata:
      labels:
        app: kubeaiwhisperer
    spec:
      serviceAccountName: kubeaiwhisperer-sa
      containers:
      - name: kubeaiwhisperer
        image: motiio/kubeaiwhisperer:6
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: kubeaiwhisperer-config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeaiwhisperer-config
data:
  AZURE_OPENAAI_ENDPOINT: ""
  AZURE_OPENAI_API_KEY: ""
  AZURE_OPENAI_VERSION: ""
  AZURE_OPENAI_DEPLOYMENT_NAME: ""
  MODEL_NAME: ""
  MAX_TOKENS: ""
  MONGODB_URI: ""
  SCAN_INTERVAL_SECONDS: ""
  LIST_NAMESPACE: ""
  ENVIRONMENT: ""

---

apiVersion: v1
kind: Service
metadata:
  name: kubeaiwhisperer-service
spec:
  selector:
    app: kubeaiwhisperer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubeaiwhisperer-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:  
    spec:
      template:
        spec:
          containers:
          - name: kubeaiwhisperer-curl
            image: curlimages/curl:7.78.0
            command: ["curl", "http://kubeaiwhisperer-service/watch-deployment"]
          restartPolicy: OnFailure
